spring:
  application:
   name: FileStorage
  datasource:
    url: jdbc:postgresql://localhost:5432/FileStorage
    password: postgres
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true
      profiles:
        active: pg_15
      lifecycle-management: start_and_stop